@startuml

folder "models" {
    database "DB"
    [ActionRun model]
}

folder "modules" {
    [some thing that could be a library]
}

folder "services" {
    [git code]
    [mailer code]
}

'folder "web_src" {
'    file "some web source"
'}

folder "routers" {
    [API]
    [web routes]
}

'folder "templates" {
'    file "go template file"
'}

'folder "tests" {
'    [integration tests]
'}

[services] -down-> [models]
[services] -down-> [modules]

[routers] -down-> [services]
[routers] -down-> [modules]
[routers] -down-> [models]
'[routers] -down-> [web_src]
'[routers] -down-> [templates]

'[tests] -down-> [models]
'[tests] -down-> [modules]
'[tests] -down-> [services]
'[tests] -down-> [web_src]
'[tests] -down-> [routers]
'[tests] -down-> [templates]

@enduml
