@startuml

'folder "/tests" {
'    [integration tests]
'}

folder "/routers" {
    package web
    package api
    'package "api/actions/runner"
    'package "web/repo/setting"
}

folder "/services" {
    package notify
    package actions
    package mailer
    package webhook

    [notify] -right[hidden]-> [actions]
    [actions] -right[hidden]-> [mailer]
    [mailer] -right[hidden]-> [webhook]
}
database "git"

folder "/models" {
    node "ActionRun model"
}
database "SQLite"

folder "/modules" {
    node "ActionRun struct"
    '[some thing that could be a library]
}

'folder "/web_src" {
'    file "some web source"
'}

'folder "/templates" {
'    'file "html template file"
'    file "/templates/mail/actions/now_done.tmpl"
'}

'[/tests] -down-> [/models]
'[/tests] -down-> [/modules]
'[/tests] -down-> [/services]
''[/tests] -down-> [/web_src]
'[/tests] -down-> [/routers]
''[/tests] -down-> [/templates]

[/routers] -down-> [/services]
[/routers] -down-> [/modules]
[/routers] -down-> [/models]
'[/routers] -down-> [/web_src]
'[/routers] -down-> [/templates]

[/services] -down-> [/models]
[/services] -down-> [/modules]
'[/services] -down[hidden]-> [/web_src]
'[/services] -down[hidden]-> [/templates]
[/services] -left-> [git]

[/models] -down-> [SQLite]

@enduml
