.PHONY: all
all: copy

.PHONY: copy
copy:
	cp ~/dlr/thesis/images/group_netlist.png .
	cp ~/dlr/thesis/images/software_overview_*.png .
	cp ~/dlr/thesis/images/connectors_*.png .
	cp ~/dlr/thesis/images/csv.png .
