name: Dev Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v1
        with:
          submodules: recursive

      # not supported by netlify
      # - name: Install Manim
      #   run: |
      #     docker pull manimcommunity/manim:stable
      #     manim() {
      #       docker run --user="$(id -u):$(id -g)" --rm -it -v "$(pwd):/manim" manimcommunity/manim manim "$@"
      #     }

      - name: Build reveal.js Presentations
        run: ./build.sh

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: public

